### ISSUE TITLE
Cherry-pick from php5-librdf?

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/flysystem-rdf#1]
See http://librdf.org/docs/php.html which is what https://github.com/linkeddata/ldphp apparently used back in the day.

**Comment by Potherca** [comment]
[EasyRDF](https://github.com/easyrdf/easyrdf/), which is used by this package, removed support for the Redland RDF Libraries in 2019 (see https://github.com/easyrdf/easyrdf/issues/327). I don't think there is much to be gained from using another solution at this point...
