### ISSUE TITLE
Metadata is checked even when the file does not exist

### ISSUE THREAD

**Issue by ylebre** [pdsinterop/flysystem-rdf#7]
https://github.com/pdsinterop/flysystem-rdf/blob/05cf9c72f023966afd74b81e4d69673617ab38fe/src/Flysystem/Adapter/Rdf.php#L181-L183

Something is going wrong in these lines - it looks to me like it should be assiging a metadata variable here?
In the lines just after this, it will try to read the file, even if the file does not exist.

**Comment by ylebre** [comment]
possibly fixed in https://github.com/pdsinterop/flysystem-rdf/commit/442234a5cf924e4c1bdef70d24d833fabe23cff8 but needs review.

**Comment by Potherca** [comment]
Reviewed. Updated the unit-test to match this new behavior. The only scenario where this _might_ be an issue is when requesting a metadata file (Solid's `describedby` property) which _does_ exist for a file which _does not_. But such a scenario should be considered wrong anyway, as the meta file should have been removed when the actual file was removed. (per the spec)
